### PR TITLE
[fix] Add -r to `pip install` instruction in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jangop**

### CODE REVIEW

**Review by gorarakelyan — APPROVED** [review]
Thanks for the contribution @jangop ! Looks good to me.

**Comment by gorarakelyan** [comment]
Waiting for @alberttorosyan to approve as well to merge the PR.

**Review by alberttorosyan — APPROVED** [review]
looks good!

**Comment by alberttorosyan** [comment]
@jangop please complete the signing cla step and we can proceed with merging 🙌

**Comment by jangop** [comment]
> @jangop please complete the signing cla step and we can proceed with merging raised_hands

I was going to, but, according to the CLA, you are SAP SE and that, like, doesn't look right, considering https://aimstack.io/about-us/.

**Comment by SGevorg** [comment]
> I was going to, but, according to the CLA, you are SAP SE and that, like, doesn't look right, considering https://aimstack.io/about-us/.

@jangop it seems you are right, weird. @gorarakelyan let's look into it ASAP.

**Comment by SGevorg** [comment]
@jangop there was a configuration issue and the cla assistant was using the default one. It should be fine now. We have changed it to the right one. Sorry for inconvenience. 
Thanks for troubleshooting the issue. 🙏

**Comment by alberttorosyan** [comment]
@jangop I've also adjusted the PR title to match our styling.
Thanks for contribution 🙌

**Pull request merged**
