### PR TITLE
[feat] Add input validations to range selectors

### PR DESCRIPTION
**Pull request by Hamik25**
- Added custom Input reusable component to UI kit
- Added unit-tests
- Added ability to pass validation pattern to inputs
- Display validation error message instead of preventing inserting invalid values
- Applied validation checkings to RangePanel inputs
- Check for inputs validity before submitting requests in Images Explorer and Run Details page tabs

### CODE REVIEW

**Comment by Hamik25** [comment]
Resolves #1255

**Review by arsengit — APPROVED** [review]

**Review by rubenaprikyan — APPROVED** [review]
Lgtm

**Review by VkoHov — APPROVED** [review]
lgtm!

**Review by rubenaprikyan — APPROVED** [review]

**Review by arsengit — APPROVED** [review]

**Review by KaroMourad — APPROVED** [review]
lgtm

**Review by VkoHov — APPROVED** [review]
lgtm!

**Review by KaroMourad — APPROVED** [review]

**Review by rubenaprikyan — APPROVED** [review]

**Pull request merged**
