### PR TITLE
[feat] Add support for Path type to the repo attribute of the Run class

### PR DESCRIPTION
**Pull request by emekaokoli19**
#2520 @tmynn @alberttorosyan could you please take a look at this

### CODE REVIEW

**Comment by alberttorosyan** [comment]
Hey @emekaokoli19! Thanks for your contribution. Will look into changes shortly.

**Review by alberttorosyan — APPROVED** [review]
Looks good!

**Comment by alberttorosyan** [comment]
@emekaokoli19 could you please update the `CHANGELOG.md` as well?

**Comment by emekaokoli19** [comment]
> @emekaokoli19 could you please update the `CHANGELOG.md` as well?

Just updated it

**Review by alberttorosyan — APPROVED** [review]
LGTM!

**Pull request merged**
