### PR TITLE
Add rm query option

### PR DESCRIPTION
**Pull request by fferflo**
Implemented the feature request from #188 since I was producing lots of superfluous dummy runs when testing my training code.

- Add a `--query` option to `aim experiment rm` that removes all runs matching the QL expression
- Add a `--dry` option to `aim experiment rm` to not delete anything and just print the deletion steps
- Add `run.duration` and `no_metrics` to QL to easily find and delete dummy runs

Example usage:
```
aim experiment rm -n experiment_name1 -q "run.duration < 1800 and run.process.finish"
aim experiment rm -q "experiment == experiment_name1 and no_metrics" --dry
```

### CODE REVIEW

**Comment by gorarakelyan** [comment]
Hi @fferflo,

Thanks for the contribution. Great enhancement! Will review the code soon 😊

**Comment by gorarakelyan** [comment]
@fferflo sorry for a late reply. The thing is, we are currently redesigning query language - mainly statements and we are going to add explicit delete statement for deleting the tracked entities(runs, metrics, steps etc). That will affect some cli changes as well. QL "expressions" will not be changed and I will make sure to come back and integrate this PR into the new interface right after the alpha version is ready. Thanks for your time and contribution!

**Comment by SGevorg** [comment]
@gorarakelyan maybe it makes sense to leave this PR On hold before we release the updated version?

**Comment by gorarakelyan** [comment]
@SGevorg yup, makes sense

**Comment by fferflo** [comment]
Sure, I'm fine with anything :)

**Pull request closed without merging**
