### PR TITLE
[feat] Added caching mechanism for sequence queries

### PR DESCRIPTION
**Pull request by mihran113**

### CODE REVIEW

**Review by alberttorosyan — COMMENTED** [review]
overall looks good.
a suggestion which might help to improve the overall code quality:
what about wrapping the cache in a class which can be accessed from any of the proxy object/view classes? if it's initialized caching is turned on and can be used.

**Comment by mihran113** [comment]
> overall looks good. a suggestion which might help to improve the overall code quality: what about wrapping the cache in a class which can be accessed from any of the proxy object/view classes? if it's initialized caching is turned on and can be used.

that might help, but we'll still need to pass down the `run_hash` to proxy and eager classes, to retrieve the correct subview of the cache, so still might be a little bit of a mess overall :)

**Comment by mihran113** [comment]
Resolves #1868

**Comment by alberttorosyan** [comment]
> > overall looks good. a suggestion which might help to improve the overall code quality: what about wrapping the cache in a class which can be accessed from any of the proxy object/view classes? if it's initialized caching is turned on and can be used.
> 
> 
> 
> that might help, but we'll still need to pass down the `run_hash` to proxy and eager classes, to retrieve the correct subview of the cache, so still might be a little bit of a mess overall :)  

fair point. lets move forward then. approving this PR

**Review by alberttorosyan — APPROVED** [review]

**Pull request merged**
