### PR TITLE
[fix] Bookmarks page cannot scroll

### PR DESCRIPTION
**Pull request by vinayan3**
This is a fix for #2653. 
The bookmarks page was not scrolling because the container CSS doesn't have overflow-y: auto. To make the page scroll
the container CSS class was removed and wrapper div was added which is sets to the height of the viewport. The screenshot below show the page scrolling for the bookmarks. The appBar is no longer in a fixed position otherwise the top of the scroll bar is hidden by the appbar.

Scrolling bookmarks:
Screenshot from 2024-07-10 18-02-29

### CODE REVIEW

**Comment by mihran113** [comment]
Hey @vinayan3! Thanks a lot for opening the PR! The changes look good. Could you please sign the CLA and also add an entry in changelog (under the unreleased section) so I can proceed to merge the PR?

**Comment by vinayan3** [comment]
@mihran113 I'm contributing as part of my time at work therefore, my company requires that someone from the legal team sign the CLA. Do you if the CLA assistant allows for this workflow where a designated signatory of a company signs on behalf of people from that organization?

**Comment by mihran113** [comment]
> @mihran113 I'm contributing as part of my time at work therefore, my company requires that someone from the legal team sign the CLA. Do you if the CLA assistant allows for this workflow where a designated signatory of a company signs on behalf of people from that organization?

@vinayan3 unfortunately the current `CLAassistant` doesn't allow for anyone else other than the PR author to sign the CLA. @SGevorg any ideas how we can tackle this?

**Comment by vinayan3** [comment]
> > @mihran113 I'm contributing as part of my time at work therefore, my company requires that someone from the legal team sign the CLA. Do you if the CLA assistant allows for this workflow where a designated signatory of a company signs on behalf of people from that organization?
> 
> @vinayan3 unfortunately the current `CLAassistant` doesn't allow for anyone else other than the PR author to sign the CLA. @SGevorg any ideas how we can tackle this?

I believe you are using the cla-assistant and from their github I found these tickets:

- https://github.com/cla-assistant/cla-assistant/issues/936
- https://github.com/cla-assistant/cla-assistant/issues/954

Could you see if your instace / usage of the CLA assistant allows for this? 

If so my company has a public Github org Aurora Open Source](https://github.com/aurora-opensource) which I'm apart of.   I can make myself public too. 

If we can sig the CLA offline like through email would this work?

**Comment by SGevorg** [comment]
Hi @vinayan3 after thinking a bit, here is what I propose to move forward.. 
For us to be able to merge this PR, the CLA must be signed from your user technically.

However for this to make legal sense, please share this URL with your legal team to sign as well.
https://cla-assistant.io/aimhubio/aim
You still will need to do it with a github account if you want to do it online.
Alternatively, you can online sign the legal doc (docusign) that's available in that link and send to hello@aimhub.io. That would do the job too.
Do you think this would work?

In the worst case scenario, we will override thie PR and just merge it ourselves. But this is not what we would prefer to do as we love contributions.

**Comment by vinayan3** [comment]
> Hi @vinayan3 after thinking a bit, here is what I propose to move forward.. For us to be able to merge this PR, the CLA must be signed from your user technically.
> 
> However for this to make legal sense, please share this URL with your legal team to sign as well. https://cla-assistant.io/aimhubio/aim You still will need to do it with a github account if you want to do it online. Alternatively, you can online sign the legal doc (docusign) that's available in that link and send to [hello@aimhub.io](mailto:hello@aimhub.io). That would do the job too. Do you think this would work?
> 
> In the worst case scenario, we will override thie PR and just merge it ourselves. But this is not what we would prefer to do as we love contributions.

I have signed and can then continue with this PR.

**Comment by vinayan3** [comment]
@mihran113 ready for review!

**Review by mihran113 — APPROVED** [review]

**Comment by mihran113** [comment]
Hey @vinayan3! Thanks a lot for your contribution, everything looks good, proceeding to merge 🎉

**Pull request merged**
