### PR TITLE
[fix] Resolve issues with outdated packages

### PR DESCRIPTION
**Pull request by KaroMourad**
- [x] Fix node version v16-17
- [x] Remove outdated packages:
        -  material-ui-audio-player
        -  node-sass
- [x] Add custom audio-player component
- [x]  Revamp UI kit

### CODE REVIEW

**Review by mihran113 — APPROVED** [review]

**Comment by Sharathmk99** [comment]
Thank you so much @KaroMourad

**Comment by Sharathmk99** [comment]
@KaroMourad do you think we can merge this PR? Thank you.

**Comment by mihran113** [comment]
Hey @Sharathmk99! I have an upcoming major feature on UI side, I'll revisit this PR after that. Don't want to merge this now as it will create a major headache to resolve all the conflicts during the development.

**Comment by Sharathmk99** [comment]
> Hey @Sharathmk99! I have an upcoming major feature on UI side, I'll revisit this PR after that. Don't want to merge this now as it will create a major headache to resolve all the conflicts during the development.

Thank you for the update.  It makes sense. 
looking forward for UI feature.

**Comment by mihran113** [comment]
Changes moved here #3254

**Pull request closed without merging**
