### PR TITLE
[feat] S3ArtifactStorage custom boto3 client parameters

### PR DESCRIPTION
**Pull request by sbatchelder**
Solution to feature request #3257 

as discussed on the Aim discord Contributing channel Nov 21st, and with blessings from gev and albert.1990

This is one of my first PRs to a 3rd party OpenSource project. If I missed something wrt the Contributing Guidelines or something else please lmk.

### CODE REVIEW

**Review by alberttorosyan — COMMENTED** [review]
@sbatchelder the changes look good! Could you please sign CLA so we can proceed with the merge?

**Comment by sbatchelder** [comment]
@alberttorosyan  Since the contribution is related to my workplace, I don't have Signatory Authority. I'm waiting on my org's legal team to review and get back to me regarding the CLA...

**Comment by sbatchelder** [comment]
@alberttorosyan I signed the CLA! and added documentation since you last reviewed this PR 👍

**Review by alberttorosyan — APPROVED** [review]
LGTM

**Pull request merged**
