### PR TITLE
[feat] Add `duration` property for `Run` objects

### PR DESCRIPTION
**Pull request by mihran113**

### CODE REVIEW

**Review by alberttorosyan — COMMENTED** [review]
looks good. should we also expose the new property in web APIs?

**Comment by mihran113** [comment]
> looks good. should we also expose the new property in web APIs?

Not sure, no such requests have been made, and also the same logic is applied in the UI, this is explicitly for queries for now

**Comment by mihran113** [comment]
Resolves #1964

**Review by alberttorosyan — APPROVED** [review]
lgtm

**Pull request merged**
