### PR TITLE
[feat] Unification of Run Custom Object APIs

### PR DESCRIPTION
**Pull request by VkoHov**
- Added `RangePanel` initial value calculation.
- Change property names in UI. Based on Run custom object API change.
- Add dynamic validation pattern usage both in images explore and run single page `RangePanel`

BE changes:
- Added common utilities for CustomObject-based APIs.
- Added class to auto-generate APIs based on the API config class.
- Adjusted existing object implementations (Image, Audio, etc.) and sequence classes.

API modifications (breaking change)
- Removed `index|record_range` and `index|record_slice`
- Removed `calc_ranges` input
- Total ranges are always calculated
- Both total and used ranges added to response schema.

### CODE REVIEW

**Comment by alberttorosyan** [comment]
resolves #1300

**Review by rubenaprikyan — APPROVED** [review]
lgtm

**Review by mihran113 — APPROVED** [review]
looks absolutely fantastic 🎉

**Comment by alberttorosyan** [comment]
> @alberttorosyan regarding the discussion we had today: maybe it's worth moving the endpoint registration part to `runs/views.py`, so all the endpoints can be accessible and visible from the same file

@mihran113 yes, will do that later today.

**Review by arsengit — APPROVED** [review]

**Pull request merged**
