### PR TITLE
[fix] replace deprecated api from mlflow

### LINKED ISSUE #2984: A bug occurs when converting from mlflow to aim.
## 🐛 Bug

Due to mlflow update [PR#6171](https://github.com/mlflow/mlflow/pull/6171), list_experiments has been replaced with search_experiments; it would be great if you guys replace it.
- [src/aimcore/cli/convert/processors/mlflow.py](https://github.com/aimhubio/aim/blob/1737b2d3573793ad30287d9335952ae7ce58a067/src/aimcore/cli/convert/processors/mlflow.py#L46)

### To reproduce

```bash
aim convert mlflow --tracking_uri 'path/to/folder/mlruns'
```

### Expected behavior

Original error code:
```
(torch2) -$ aim convert mlflow --tracking_uri 'path/to/folder/mlruns'
Traceback (most recent call last):
  File "/home/mtk30765/.conda/envs/torch2/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/aim/cli/convert/commands.py", line 66, in convert_mlflow
    parse_mlflow_logs(repo_inst, tracking_uri, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/aim/cli/convert/processors/mlflow.py", line 46, in parse_mlflow_logs
    experiments = client.list_experiments()
AttributeError: 'MlflowClient' object has no attribute 'list_experiments'
```

Once you replace `list_experiments` to `search_experiments`, it will run perfectly.

### Environment

- Aim Version (e.g., 3.0.1): 3.17.5
- MLflow: 2.5.0
- Python version: 3.9.15
- pip version: 23.2.1
- OS (e.g., Linux): Linux Ubuntu 18.04.6 LTS x86_64

### Additional context

I can create a PR if you guys want me to do so, or whatever you guys like.

### PR DESCRIPTION
**Pull request by Mai0313**
To fix #2984, we simply need to replace `list_experiment` with `search_experiments` in [src/aimcore/cli/convert/processors/mlflow.py](https://github.com/aimhubio/aim/blob/1737b2d3573793ad30287d9335952ae7ce58a067/src/aimcore/cli/convert/processors/mlflow.py#L46).

By the way, I've been working at a company for a year, but I've never submitted a PR to an open source project before. I hope this contribution can be of help!

### CODE REVIEW

**Comment by alberttorosyan** [comment]
@Mai0313 thanks for your contribution! Congrats on first PR on open-source repo 🙌 

Seems the `search_experiments` method was added in mlflow `1.28.0`; would be great to add a version check to prevent failures when lower version of mlflow is installed.

**Comment by Mai0313** [comment]
For this commit #7c2f9ff, I'm aware that mlflow provides an API called mlflow.version. However, I chose to use the version module from packaging instead to avoid potential issues if mlflow changes their API naming in the future. [Source](https://github.com/aimhubio/aim/pull/2985/files#diff-5efc31e4e9bc86fa1275d2fe96f947b1329fbf986f3631f2a6eba73606a0cbaeR48)

I've also added some notes above the code. I didn't see any pre-commit hooks in place, but I tried to adhere to the coding style that you guys have been using. Please let me know if there are any issues.

**Comment by alberttorosyan** [comment]
@Mai0313 sorry for late response; somehow missed your last commit 🙌 

> For this commit #7c2f9ff, I'm aware that mlflow provides an API called mlflow.version. However, I chose to use the version module from packaging instead to avoid potential issues if mlflow changes their API naming in the future

Fully agree with this!

**Comment by alberttorosyan** [comment]
> @alberttorosyan Thank you for your response, and no worries! I will attempt to rectify the `sanity checks`. Due to the policies at my workplace, MediaTek, I am not permitted to upload anything. Consequently, I was unable to test the action before pushing it. I will address this issue as soon as possible, likely after work today.

@Mai0313, no need to take any actions on this. Sanity checks are broken at this moment, since we're preparing the new major release (in many ways incompatible with the version 3.x)

**Comment by Mai0313** [comment]
@alberttorosyan Oh, sounds fantastic about the update; however, what should I do next, it is my first time to do this. 
I guess we should wait this until you guys are done for update.

**Comment by tomaz-suller** [comment]
Sorry but any reason why this has not been merged? Conversion still fails because of this quite simple fix.

@Mai0313 @alberttorosyan I'm willing to help if needed, I just couldn't figure out what the problem is but it looked like it had to do with the CI and the logs aren't available any more.

**Comment by tomaz-suller** [comment]
While we're at it we might as well replace `mlflow.tracking.client.MlflowClient` with `mlflow.MlflowClient` as suggested in [the example](https://mlflow.org/docs/latest/python_api/mlflow.client.html#mlflow.client.MlflowClient) in MLFlow docs. It's of course the same thing but Pylance resolves the type of the latter but not of the former, and so should other type checking tools I assume, which could've helped spot this sooner. 

(I tried adding this comment as a review but GitHub complained that the repo the PR came from didn't exist any more.)

**Comment by Mai0313** [comment]
@tomaz-suller  I think this pr is pretty much done, but i forgot the reason why it is not merged haha

**Comment by Mai0313** [comment]
reopen it.

**Comment by jaredxfeng** [comment]
Whoopsies bug is still here in 2026.

**Pull request closed without merging**
