### PR TITLE
Add Keras-Tuner integration

### LINKED ISSUE #422: Integration with Keras Tuner
Hi, I was wondering if this integrated with the tf Keras hyperparameter tuner and ,if so, are there any examples you could point me to? Thank you, great project.

### PR DESCRIPTION
**Pull request by Khazhak**
Added Keras-Tuner integraation. I found a way to make a Callback as most of the other integrations, without creating a package as we planned earlier.

Closes #422.

### CODE REVIEW

**Comment by gorarakelyan** [comment]
@khazhak I think we should store each trial inside separate session/run instead of storing within one run and separating by `trial_id` context argument.

**Comment by karan2801** [comment]
@gorarakelyan Please assign me this task if no one else is working on it currently. Thanks in advance.

**Comment by gorarakelyan** [comment]
@karan2801 just did ✅

**Comment by gorarakelyan** [comment]
closing this PR. The further development moved here: https://github.com/aimhubio/aim/pull/2052

**Pull request closed without merging**
