### PR TITLE
Add remaining endpoints

### PR DESCRIPTION
**Pull request by mihran113**
List of endpoints:
 - project/activity
 - project/params
 - search/run
 - {run_id}/metrics
 - {run_id}/params
 - {run_id}/metrics/batch

### CODE REVIEW

**Comment by mihran113** [comment]
Will restructure the aim/web/api directory in a separate branch

**Review by alberttorosyan — APPROVED** [review]
@mihran113 looks great. Just one small comment; could you please rename `run.created_at` to `run.started_at`? We do have property with same name on ModelMappedRun object and once we move to unified Run object, this might cause confusion.

**Comment by mihran113** [comment]
> @mihran113 looks great. Just one small comment; could you please rename `run.created_at` to `run.started_at`? We do have property with same name on ModelMappedRun object and once we move to unified Run object, this might cause confusion.

yeah, for sure, will change

**Review by gorarakelyan — APPROVED** [review]
looks great

**Pull request merged**
