### PR TITLE
[feat] Expose context in the PyTorch Ignite

### PR DESCRIPTION
**Pull request by tmynn**
Developed a new feature that allows an initial context to be passed as an argument to the AimLogger

### CODE REVIEW

**Comment by tmynn** [comment]
Resolves #2638

**Review by alberttorosyan — COMMENTED** [review]
@tmynn, looks good!
One question I have is the following: what if the passed context already has a 'subset' key? 🤔 
Would it be reasonable to not overwrite its value in this case?

**Comment by tmynn** [comment]
> @tmynn, looks good! One question I have is the following: what if the passed context already has a 'subset' key? 🤔 Would it be reasonable to not overwrite its value in this case?

Good point @alberttorosyan, should we rename the upcoming 'subset' key in that case?

**Comment by mihran113** [comment]
> > @tmynn, looks good! One question I have is the following: what if the passed context already has a 'subset' key? 🤔 Would it be reasonable to not overwrite its value in this case?
> 
> Good point @alberttorosyan, should we rename the upcoming 'subset' key in that case?

I guess user's input must have higher priority, so if the `subset` is already present, we can leave it as it is, and don't override it afterwards

**Review by alberttorosyan — APPROVED** [review]
lgtm

**Review by mihran113 — APPROVED** [review]

**Pull request merged**
