### PR TITLE
[feat] Add capture_terminal_logs flag description on docstring

### PR DESCRIPTION
**Pull request by tmynn**
The `Run` class's docstring has been updated to include a description for the `capture_terminal_logs` flag.

### CODE REVIEW

**Comment by tmynn** [comment]
Resolved #2688

**Review by alberttorosyan — APPROVED** [review]
lgtm

**Comment by mihran113** [comment]
> Resolved #2688

@tmynn this seems to be the wrong link, it just points at the current PR

**Comment by tmynn** [comment]
Added docstrings to all callbacks/loggers and reformatted (black formatting) both the integration files and examples.
Relocated all Aim related parameters (repo, experiment_name etc) to be the first by a specific order.

**Comment by mihran113** [comment]
@tmynn can we go back to single quotes? As they're used for the rest of the code. The rest looks good.

**Review by mihran113 — APPROVED** [review]

**Pull request merged**
