### PR TITLE
Add basic K8S integration/deployment docs

### PR DESCRIPTION
**Pull request by flaviuvadan**
This PR adds a brief tutorial on how to deploy Aim to Kubernetes. This might help with adoption as there are many use cases for companies that have a group of ML practitioners who mainly extract value from Aim through the core visualization features, rather than local CLI utilization to see runs. By deploying Aim to K8S, users have access to a centralized spot for visualizing Aim runs, provided they are performing remote training. This PR adds the tutorial for this setup. 

When #1074 was filed we discussed the opportunity of making cloud provider specific tutorials. However, upon further review, engineers who are aware of how to structure a K8S cluster with the setup presented in this tutorial will likely know their specific context so that they create/deploy a `ReadWriteMany` volume for Aim.

Contributes to: https://github.com/aimhubio/aim/issues/1074

### CODE REVIEW

**Comment by gorarakelyan** [comment]
@flaviuvadan just went over the guide, it's amazing! thanks so much for the effort 😊 very descriptive and concise!

And, congrats on the first submitted PR! 🚀 

I noticed there is a problem with loading images? Would love to help with that.

**Comment by flaviuvadan** [comment]
> I noticed there is a problem with loading images? Would love to help with that.

I noticed that too! You may have noticed multiple commits trying to get GitHub to render them. I use MacDown to write Markdown on my machine and they render fine in that one. I looked through multiple guides and the syntax seems fine to me. Any chance you noticed something odd about it?

**Review by SGevorg — APPROVED** [review]
lgtm

**Comment by SGevorg** [comment]
@flaviuvadan just reviewed the PR. Awesome stuff. Thanks for the effort! 
Really nice and concise guide. 
Congrats on the first contribution 🎉

**Review by gorarakelyan — APPROVED** [review]
approved ✅

**Comment by gorarakelyan** [comment]
merged the PR 🚀

**Pull request merged**
