### PR TITLE
[fix] Fix pytorch_lightning aliases issue

### LINKED ISSUE #2746: Handling for aliases of PyTorch Lightning
## 🐛 Bug

Starting from PyTorch Lightning 1.8, this package has been renamed to `Lightning`. While both `lightning` and `pytorch_lightning` are in use as a package (`lightning` is a superset package for `pytorch_lightning` now.

This has caused a problem that `aim`'s code only support for PyTorch Lightning when `pytorch_lightning` is installed. While `lightning` is installed for some other users/developers, they will find that `aim` will wrongly suggest that they have not installed `Pytorch Lightning`.

Since parallel distribution of both `lightning` and `pytorch_lightning` would stays for a long time. It may be necessary to support both package in 

### To reproduce

Use `pip install lightning` instead of `pip install pytorch_lightning`

### Expected behavior

pytorch lightning addons should work for both those who installed `lightning` package and `pytorch-lightning` package.

### Environment

- Aim Version (e.g., 3.0.1): latest
- Python version: 3.10.1
- pip version
- OS (e.g., Linux): Linux
- PyTorch Lightning >= 1.8.0

### Additional context

None

### PR DESCRIPTION
**Pull request by popfido**
Resolves #2746 

**Notes**

Have been manually tested via a local package install with the lightning `AimLogger`.

### CODE REVIEW

**Comment by mihran113** [comment]
Hey @popfido! Sorry for a late response. The PR looks good. can I ask you to use `aimhubio:release/3.17.x` this branch as a destination, so we can include the fix in the upcoming patch release?

**Comment by popfido** [comment]
Sure, I'll 

> Hey @popfido! Sorry for a late response. The PR looks good. can I ask you to use `aimhubio:release/3.17.x` this branch as a destination, so we can include the fix in the upcoming patch release?

Sure

**Comment by popfido** [comment]
Hey @mihran113 I've already switch from merging to main to `aimhubio:release/3.17.x`.

**Comment by mauricekraus** [comment]
Can this be merged?

**Review by alberttorosyan — APPROVED** [review]
Looks good! Approving and merging this PR as it is relevant again.

**Pull request merged**
