### PR TITLE
[fix] Table column's sort functionality issue in params and scatters explorers

### PR DESCRIPTION
**Pull request by rubenaprikyan**
- Fix table column's sorting issue in Params Explorer
- Fix table column's sorting issue in Scatters Explorer
- Fix table column's sorting issue in Metrics Explorer
- Fix table column's sorting issue in Images Explorer

### CODE REVIEW

**Comment by rubenaprikyan** [comment]
Resolves #1259

**Review by roubkar — APPROVED** [review]

**Comment by VkoHov** [comment]
@rubenaprikyan jan. Please check the Metrics Explore and Images Explore tables too. We have the same problem there. It is working but after descending order from the column it changes to ascending. We need it to remove the order as it is in other explores.

**Review by VkoHov — APPROVED** [review]

**Comment by rubenaprikyan** [comment]
> @rubenaprikyan jan. Please check the Metrics Explore and Images Explore tables too. We have the same problem there. It is working but after descending order from the column it changes to ascending. We need it to remove the order as it is in other explores.

Fixed

**Comment by rubenaprikyan** [comment]
> @rubenaprikyan jan. Please check the Metrics Explore and Images Explore tables too. We have the same problem there. It is working but after descending order from the column it changes to ascending. We need it to remove the order as it is in other explores.

Fixed

**Pull request merged**
