### PR TITLE
[fix] Use `packaging.version` to parse version strings

### LINKED ISSUE #2316: Pytorch Lightning Adapter expects versions to consist of `int`s
The [Pytorch Lightning Adapter](https://github.com/aimhubio/aim/blob/15e394cc39b9def1a283f7e1ca7e6aac7a6d2027/aim/sdk/adapters/pytorch_lightning.py) in 3.14.3 extracts a version tuple from the version string. It expects all parts to map to `int`:

```python
    def versiontuple(v):
        return tuple(map(int, (v.split("."))))
```

I noticed the problem when I received the following exception: `ValueError: invalid literal for int() with base 10: 'post1'`

I suggest using [`packaging.version.parse`](https://packaging.pypa.io/en/latest/version.html#packaging.version.parse), so I'll submit a PR soonish.

### PR DESCRIPTION
**Pull request by jangop**
Closes #2316.

### CODE REVIEW

**Comment by jangop** [comment]
@gorarakelyan that is entirely understandable. However, `packaging` is not just any dependency. You are using `setuptools` to package aim, and so, you already have access to `packaging`. From what I understand.

Personally, I consider `packaging` almost-stdlib and version string parsing is not something I think anyone should reimplement:  [PEP440](https://peps.python.org/pep-0440/).

**Comment by alberttorosyan** [comment]
> @gorarakelyan that is entirely understandable. However, packaging is not just any dependency. You are using setuptools to package aim, and so, you already have access to packaging. From what I understand.

As I recall, `setuptools` is the build-time only dependency and with the isolated builds it should not affect environment where aim is installed.

> Personally, I consider packaging almost-stdlib and version string parsing is not something I think anyone should reimplement: [PEP440](https://peps.python.org/pep-0440/).

@jangop, fair point 🙌  @gorarakelyan, just checked the `packaging` package size, the universal wheel is only ~40KB, so maybe worth considering it 🤔 ?

CC @mahnerak

**Comment by mahnerak** [comment]
We had this: https://github.com/aimhubio/aim/pull/2107#discussion_r973485036
Not sure why we didn't resolve it.

> setuptools is the build-time only dependency and with the isolated builds it should not affect environment where aim is installed.

That's right. 
`setuptools` and `packaging` are not stdlib, and are available for aim only during (isolated) build. The `pip` itself is able to compare versions, but even `pip` is not always available. 

> and version string parsing is not something I think anyone should reimplement: 

Totally agree. I think we better add a new dependency rather implementing our parser. Most of the python environments already have `packaging`, so even that `40kb` is rarely going to be installed just for `aim`.

**Comment by jangop** [comment]
> Most of the python environments already have `packaging`, so even that `40kb` is rarely going to be installed just for `aim`.

That's a better version of what I was trying to say. 😅

**Comment by jangop** [comment]
Oh, in the commit I did not add `setuptools` to `setup.py`, because I really do not know which version to pick.

**Comment by gorarakelyan** [comment]
Makes a lot of sense. Let's just make sure to put really loose version boundaries to avoid dependencies incompatibilities (if there may be any) during installation.

**Comment by jangop** [comment]
> Makes a lot of sense. Let's just make sure to put really loose version boundaries to avoid dependencies incompatibilities (if there may be any) during installation.

Do you / does anyone know of a tool to figure out the earliest version / point in time when a certain function / functionality was added to a given dependency? This is a problem I always struggle with.

**Comment by alberttorosyan** [comment]
> > Makes a lot of sense. Let's just make sure to put really loose version boundaries to avoid dependencies incompatibilities (if there may be any) during installation.
> 
> Do you / does anyone know of a tool to figure out the earliest version / point in time when a certain function / functionality was added to a given dependency? This is a problem I always struggle with.

Not aware of any such tool... Usually I check the release notes, but in this case there's nothing mentioned... Though I've looked at the github repo; version `15.0` already has the `parse` function.

**Comment by jangop** [comment]
> > > Makes a lot of sense. Let's just make sure to put really loose version boundaries to avoid dependencies incompatibilities (if there may be any) during installation.
> > 
> > 
> > Do you / does anyone know of a tool to figure out the earliest version / point in time when a certain function / functionality was added to a given dependency? This is a problem I always struggle with.
> 
> Not aware of any such tool... Usually I check the release notes, but in this case there's nothing mentioned... Though I've looked at the github repo; version `15.0` already has the `parse` function.

Thanks a million. I'll add it.

**Review by alberttorosyan — APPROVED** [review]

**Comment by alberttorosyan** [comment]
@jangop, approved and merged PR. Thanks for contribution 🙌

**Pull request merged**
