### PR TITLE
[feat] Extend Run to support tensorboard logs real-time sync

### LINKED ISSUE #2015: Sync tensorboard event log file in real-time
### Motivation
Sync tensorboard event log file in real-time

### Pitch
Accept new parameter for Run class called sync_tensorboard_dir to accept tensorboard event log directory and start a separate thread to monitor the file events and sync if any changes. Every subfolder inside the tensorboard event log directory becomes entity

### PR DESCRIPTION
**Pull request by Sharathmk99**
Fixes #2015

### CODE REVIEW

**Comment by Sharathmk99** [comment]
@mahnerak  @alberttorosyan @SGevorg Review please?
Is this feature makes sense?
Thanks

**Comment by alberttorosyan** [comment]
@Sharathmk99 thanks for your contribution 🙌
The idea we've been exploring for a while is to refactor `run.py` file and keep the Run class as a basic interface for tracking/logging. In this context everything else currently included in Run becomes plugin. For example, we can have 
`TBRun` plugin derived from `Run` and extending the functionality to keep track of the tb event files.
`SystemResourcesRun` plugin derived from `Run` and tracking CPU/GPU/memory usage in a background.

Do you think it would make sense to adjust implementation accordingly?

**Comment by Sharathmk99** [comment]
> @Sharathmk99 thanks for your contribution 🙌 The idea we've been exploring for a while is to refactor `run.py` file and keep the Run class as a basic interface for tracking/logging. In this context everything else currently included in Run becomes plugin. For example, we can have `TBRun` plugin derived from `Run` and extending the functionality to keep track of the tb event files. `SystemResourcesRun` plugin derived from `Run` and tracking CPU/GPU/memory usage in a background.
> 
> Do you think it would make sense to adjust implementation accordingly?

Yes of-course it makes more sense. I understand how much code present in `run.py`.
I can refractor the code to align with the new changes. Do you already have draft implementation in some branch?
Many thanks!

**Comment by alberttorosyan** [comment]
> > @Sharathmk99 thanks for your contribution 🙌 The idea we've been exploring for a while is to refactor `run.py` file and keep the Run class as a basic interface for tracking/logging. In this context everything else currently included in Run becomes plugin. For example, we can have `TBRun` plugin derived from `Run` and extending the functionality to keep track of the tb event files. `SystemResourcesRun` plugin derived from `Run` and tracking CPU/GPU/memory usage in a background.
> > Do you think it would make sense to adjust implementation accordingly?
> 
> Yes of-course it makes more sense. I understand how much code present in `run.py`. I can refractor the code to align with the new changes. Do you already have draft implementation in some branch? Many thanks!

@Sharathmk99 unfortunately we don't have any branch with reference implementation yet. We can discuss the design principles here and implement the new functionality as a plugin. Afterwards, the rest of the code can be easily refactored.

**Comment by Sharathmk99** [comment]
> > > @Sharathmk99 thanks for your contribution 🙌 The idea we've been exploring for a while is to refactor `run.py` file and keep the Run class as a basic interface for tracking/logging. In this context everything else currently included in Run becomes plugin. For example, we can have `TBRun` plugin derived from `Run` and extending the functionality to keep track of the tb event files. `SystemResourcesRun` plugin derived from `Run` and tracking CPU/GPU/memory usage in a background.
> > > Do you think it would make sense to adjust implementation accordingly?
> > 
> > 
> > Yes of-course it makes more sense. I understand how much code present in `run.py`. I can refractor the code to align with the new changes. Do you already have draft implementation in some branch? Many thanks!
> 
> @Sharathmk99 unfortunately we don't have any branch with reference implementation yet. We can discuss the design principles here and implement the new functionality as a plugin. Afterwards, the rest of the code can be easily refactored.

@alberttorosyan Yes sure. Can you share the ideal bit more, so I can start implementing? Thanks

**Comment by alberttorosyan** [comment]
@Sharathmk99 sorry for late response.
I think we can select the following approach:
1st of all, separate the new functionality for keeping track of the tensorboard logs into a separate mixin class. This can be implemented as a separate module inside `ext/`.
Next step would be, implementing a new: `TBConverterRun` class, which will derive from both base `Run` and the newly implemented mixin, thus enabling the track() method for the mixin itself, and getting the behavior of a base `Run`.
As you may probably noticed, there's a `RunAutoClean` helper class, responsible for the Run's resources cleanup. The implementation might require some tweaks to make sure the clean-up is done properly and in correct order, regardless the number of mixin classes in the custom `*Run` classes.

**Comment by alberttorosyan** [comment]
Hey @Sharathmk99! I just pushed some changes according the discussion we had above. Now there's a new `Run` class in `aim.ext.tensorboard_tracker` with cleaner interface (log dir is mandatory, no additional arguments). Please take a look.

**Comment by alberttorosyan** [comment]
@mihran113 @gorarakelyan since I've also contributed to the PR, could you please review the changes?

**Comment by alberttorosyan** [comment]
@gorarakelyan @mihran113, please take a look

**Review by mihran113 — APPROVED** [review]

**Comment by alberttorosyan** [comment]
@Sharathmk99 I've pushed some changes to resolve conflicts with `main` branch. There were some big changes related to run resources management.
The only remaining step is to complete CLA signing step.

**Comment by Sharathmk99** [comment]
> @Sharathmk99 I've pushed some changes to resolve conflicts with `main` branch. There were some big changes related to run resources management.
> The only remaining step is to complete CLA signing step.

Done. Thank you so much

**Pull request merged**
