### PR TITLE
add sqlite Run every time new Run is started

### PR DESCRIPTION
**Pull request by alberttorosyan**
Removed all the logic associated with the case when sqlite Run is missing. Added `run.experiment = 'default'` for newly created runs

### CODE REVIEW

**Comment by alberttorosyan** [comment]
Currently the implementation of `run.props` assumes that sqlite Run model is created first time Run object is initialized (in write mode). Since unit-tests truncate sqlite db every time per test-suite, this breaks all tests run (though 1 test-suite passes). Need to figure-out the way to fix tests without altering this logic.

**Comment by mihran113** [comment]
> Currently the implementation of `run.props` assumes that sqlite Run model is created first time Run object is initialized (in write mode). Since unit-tests truncate sqlite db every time per test-suite, this breaks all tests run (though 1 test-suite passes). Need to figure-out the way to fix tests without altering this logic.

Maybe we need to truncate rocksdb data as well, and create new runs for each test case as well? To provide total independence for each test case?

**Comment by alberttorosyan** [comment]
> > Currently the implementation of `run.props` assumes that sqlite Run model is created first time Run object is initialized (in write mode). Since unit-tests truncate sqlite db every time per test-suite, this breaks all tests run (though 1 test-suite passes). Need to figure-out the way to fix tests without altering this logic.
> 
> Maybe we need to truncate rocksdb data as well, and create new runs for each test case as well? To provide total independence for each test case?

Will definelty get to that at some point.

**Review by mihran113 — APPROVED** [review]
looks good, we'll take care of the unit tests after

**Pull request merged**
