### PR TITLE
Add ability to provide custom base path for API

### PR DESCRIPTION
**Pull request by roubkar**
- Add `--base_path` arg for `aim up` command in CLI
- Use `Jinja` templating for injecting `base_path` into `index.html`
- Use `API_BASE_PATH` as a prefix for accessing API endpoints from UI

### CODE REVIEW

**Comment by roubkar** [comment]
Resolves https://github.com/aimhubio/aim/issues/1096

**Review by alberttorosyan — APPROVED** [review]
looks good.
really love this part  `if (globalScope.API_BASE_PATH === '{{ base_path }}')` 😄

**Review by rubenaprikyan — APPROVED** [review]
lgtm!

**Comment by dshakey** [comment]
thanks for adding ,but cant it to work. i dont see the path being passed and static files are still on root /

`aim up -h 0.0.0.0 --base-path /my-path --dev`
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
INFO  [sqlalchemy.engine.Engine] SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.Engine] [generated in 0.00011s] ()
Running Aim UI on repo `<Repo#5637476011149268472 path=/home/dshakes1/.aim read_only=None>`
Open http://0.0.0.0:43800
Press Ctrl+C to exit
INFO:     Will watch for changes in these directories: ['/home/dshakes1/conda/lib/python3.7/site-packages/aim']
INFO:     Uvicorn running on http://0.0.0.0:43800 (Press CTRL+C to quit)
INFO:     Started reloader process [4748] using statreload
INFO:     Started server process [4750]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
^C
INFO:     Shutting down
INFO:     Finished server process [4750]
INFO:     ASGI 'lifespan' protocol appears unsupported.
```

image

**Comment by mihran113** [comment]
> thanks for adding ,but cant it to work. i dont see the path being passed and static files are still on root /
> 
> `aim up -h 0.0.0.0 --base-path /my-path --dev`
> 
> ```
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
> INFO  [sqlalchemy.engine.Engine] [raw sql] ()
> INFO  [sqlalchemy.engine.Engine] SELECT alembic_version.version_num 
> FROM alembic_version
> INFO  [sqlalchemy.engine.Engine] [generated in 0.00011s] ()
> Running Aim UI on repo `<Repo#5637476011149268472 path=/home/dshakes1/.aim read_only=None>`
> Open http://0.0.0.0:43800
> Press Ctrl+C to exit
> INFO:     Will watch for changes in these directories: ['/home/dshakes1/conda/lib/python3.7/site-packages/aim']
> INFO:     Uvicorn running on http://0.0.0.0:43800 (Press CTRL+C to quit)
> INFO:     Started reloader process [4748] using statreload
> INFO:     Started server process [4750]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> ^C
> INFO:     Shutting down
> INFO:     Finished server process [4750]
> INFO:     ASGI 'lifespan' protocol appears unsupported.
> ```
> 
> image

Hey @dshakey. Thanks for sharing this, we also realized initial issue was incomplete and wouldn't solve the end to end problem. We've opened a new issue which will hopefully really fix the problem. You can track it here #1117.

Please feel free to add more context if something is missing.

**Comment by gorarakelyan** [comment]
Hi @dshakey,

We just released Aim v3.3.0 with base path fix. Now it will redirect all the calls to "/my-path" for example.
Please try it out and check if it works.

**Pull request merged**
