### PR TITLE
[feat] Add x-client header to every grpc request

### PR DESCRIPTION
**Pull request by mihran113**

### CODE REVIEW

**Review by alberttorosyan — COMMENTED** [review]
changes look good 🙌 
lets see if there's anything else needed for implementing sticky sessions before merging.

**Review by alberttorosyan — APPROVED** [review]
@mihran113 lets change the base branch to `release/3.15.x` and ship with the next patch

**Comment by mihran113** [comment]
> @mihran113 lets change the base branch to `release/3.15.x` and ship with the next patch

going to open a new one, to not create a total mess

**Comment by mihran113** [comment]
All the changes moved here: 
https://github.com/aimhubio/aim/pull/2439

**Pull request closed without merging**
